disabled_rules: # rule identifiers to exclude from running
  - line_length
#   - force_try
#   - force_cast
#   - todo
#   - cyclomatic_complexity
#   - function_parameter_count

included: # paths to include during linting. `--path` is ignored if present.
  - ClangNotifications
  - ClangNotificationsDemoApp
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 500 # error
function_body_length:
  - 100 # warning
  - 200 # error
# or they can set both explicitly
file_length:
  warning: 400
  error: 800
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 200
    error: 300
identifier_name:
  min_length: # only min_length
    error: 0  # only error
    warning: 2

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
